# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    checkLatest: true

- script: |
        npm install
        npm run build
  displayName: 'npm install and build'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      # Write your commands here
      
      echo "ls"
      echo "pwd"
      echo "##vso[task.setvariable variable=NAME]$(awk '/version/{print $2}' /home/vsts/work/1/s/package.json)
      echo "##vso[task.setvariable variable=VERSION]$(awk '/version/{print $2}' /home/vsts/work/1/s/package.json)

