# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- development

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseNode@1
  inputs:
    checkLatest: true

- script: |
        npm install
        npm run build
  displayName: 'npm install and build'