apiVersion: apps/v1
kind: Deployment
metadata:
  name: azurepipeline-deployment
  namespace: testing
  labels:
    app: api-randomtest
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-randomtest
  template:
    metadata:
      labels:
        app: api-randomtest
    spec:
      containers:
        - name: api-randomtest
          image: gfmmtesting.azurecr.io/g-f-m-m-testing/tp-api-randomtest:#{Build.BuildId}#
          ports:
            - containerPort: 3000
              name: http
      imagePullSecrets:
         - name: azure